In [7]:
import numpy as np

In [8]:
X = np.array([
    [15,16,16,15,14],
    [17,14,15,16,16],
    [13,15,12,13,15],
    [18,16,17,17,15],
    [14,13,16,15,14],
    [18,16,17,16,15],
    [15,14,14,14,14],
    [16,11,12,14,12],
    [17,16,13,15,15],
    [18,12,14,15,13],
    [12,13,15,13,12],
    [13,16,12,13,15],
    [14,17,17,16,16],
    [12,18,13,13,17],
    [13,15,12,12,14],
    [14,16,13,13,13],
    [16,17,15,15,16],
    [16,15,15,16,16],
    [15,14,14,16,13],
    [17,17,14,17,16]]);
print(X.shape)    

(20, 5)


##### Computing PCA using sklearn

In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
pca.fit(X)
print("eigenvalues o λ (magnitud de vectores)")
print(pca.explained_variance_ )
print("eigenvector o v (dirección de vector o vector unidad) - transpuesto")
print(pca.components_)
print()
print(pca.explained_variance_ratio_)
print(pca.singular_values_)

eigenvalues o λ (magnitud de vectores)
[ 6.93217635  4.75885015  1.89855029  0.5743376   0.30187509]
eigenvector o v (dirección de vector o vector unidad) - transpuesto
[[ 0.61629956  0.1844356   0.4970166   0.53141929  0.23817305]
 [-0.37032067  0.7742203   0.01346735 -0.07904285  0.50696784]
 [-0.54409094 -0.12181173  0.79766596  0.0294354  -0.2280121 ]
 [ 0.26796562  0.57621699  0.07269114 -0.25349279 -0.72568989]
 [-0.33940672  0.14036494 -0.33352382  0.80387856 -0.32808823]]

[ 0.47921175  0.32897272  0.13124415  0.03970316  0.02086821]
[ 11.47655657   9.50884603   6.00603492   3.30339437   2.39491684]


#### Computing PCA using covariance method

In [20]:
n,p = X.shape

# computing PCA using covariance method (see wikipedia)
u = np.mean(X, axis=0)
h = np.ones((n,1))
M = X - h * u.T 
S = np.cov(M.T)
_lambda,_v = np.linalg.eig(S)

print("covariance matrix")
print(S)

print("eigenvalues o λ (magnitud de vectores)")
print(_lambda)
print(np.cumsum(_lambda)/sum(_lambda), " (% acum)") 

print("eigenvector o v (dirección de vector o vector unidad)")
print(_v)

covariance matrix
[[ 3.92368421 -0.37631579  1.32105263  2.25789474  0.28157895]
 [-0.37631579  3.31315789  0.51052632  0.33157895  1.97105263]
 [ 1.32105263  0.51052632  2.95789474  1.77894737  0.51052632]
 [ 2.25789474  0.33157895  1.77894737  2.22105263  0.7       ]
 [ 0.28157895  1.97105263  0.51052632  0.7         2.05      ]]
eigenvalues o λ (magnitud de vectores)
[ 6.93217635  4.75885015  1.89855029  0.30187509  0.5743376 ]
[ 0.47921175  0.80818448  0.93942863  0.96029684  1.        ]  (% acum)
eigenvector o v (dirección de vector o vector unidad)
[[-0.61629956  0.37032067 -0.54409094 -0.33940672 -0.26796562]
 [-0.1844356  -0.7742203  -0.12181173  0.14036494 -0.57621699]
 [-0.4970166  -0.01346735  0.79766596 -0.33352382 -0.07269114]
 [-0.53141929  0.07904285  0.0294354   0.80387856  0.25349279]
 [-0.23817305 -0.50696784 -0.2280121  -0.32808823  0.72568989]]
